"Elizabeth is hungry",
"He saw the frog with the telescope.",
"Stand on your head",
"Grapes become shriveled in the sun",
"The balloon is green.",
"Judy runs.",
"Four young soldiers led the troops into battle.",
"The soft, hypnotic motion of the waves serenaded us with tender songs of happier times and finally lulled us into a peaceful, dreamless sleep.",
"The soft, purring kitten nestled in the child's lap.",
"Airplanes fly.",
"Judy and her dog run on the beach every morning.",
"The audience littered the theatre floor with torn wrappings and spilled popcorn.",
"Everybody went fishing, even the dog.",
"Ottawa is the capital of Canada.",
"The distinction between deconstruction and post-modernism eludes me.",
"He asked which path leads back to the lodge.",
"There were three stray kittens cowering under our porch steps this morning.",
"Stand on your head",
"A piece of pepperoni pizza would satisfy his hunger.",
